### PR TITLE
Addition of links for code and data for submission 5

### PR DESCRIPTION
**Pull request by pernisch**

### CODE REVIEW

**Review by luigi-asprino — CHANGES_REQUESTED** [review]
Hi, 
it seems that you changed links of the wrong paper.

**Comment by dgarijo** [comment]
@romanka,
can you please add the proper snippets to the accepted papers page too (https://github.com/k-cap/k-cap.github.io/blob/master/2021/accepted.html), to be consistent?
And the corresponding triples to the KG in https://github.com/k-cap/k-cap.github.io/tree/master/2021/rdf so we don't miss your resources if someone queries the full dataset. Thanks in advance!

**Comment by luigi-asprino** [comment]
sorry, my bad :-)

**Comment by dgarijo** [comment]
@romanka, please have a look at my comment, which still applies. Thanks!

**Comment by dgarijo** [comment]
@romanka, we would like to make your resources live. Can you please incorporate my comment when you have the chance?

**Comment by pernisch** [comment]
so sorry about the late reply... I was not aware of the notification :see_no_evil:

**Comment by dgarijo** [comment]
No problem, but the comment still applies :)

**Comment by dgarijo** [comment]
No problem, but the comment still applies :)

**Pull request merged**
